- link:
    ~/.gitconfig:
- shell:
    - command: read git_email && sed -i '' "s/AUTHOREMAIL/$git_email/g" gitconfig
      stdin: true
      description: What email do you want to use for Git?
      quiet: true
