# expected to be ran after ./install

- defaults:
    link:
      create: true
      relink: true

- shell:
    - git submodule sync --recursive
    - git submodule update --init --recursive --force --remote
